#!/usr/bin/env bash
# personal setup script
set -o pipefail

BASE_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${BASE_DIR}" || exit 1

# deps I use from upstream, might as well install them here
upstream_module_dependencies() {
	hpi_module my.github.ghexport || return $?
	hpi_module my.browser.export || return $?
	hpi_module my.reddit.pushshift || return $?
	hpi_module my.reddit.rexport || return $?
	hpi_module my.pdfs || return $?
	hpi_module my.smscalls || return $?
	hpi_module my.coding.commits || return $?
}

module_deps() {
	upstream_module_dependencies || return $?
	pip_install 'git+https://github.com/karlicoss/arctee' || return $?
	hpi_module my.old_forums || return $?
}

pmain() {
	pip_install -e . || return $?
	module_deps || prompt_if_fails || return $?
}

declare MY_MODULES
MY_MODULES="$(realpath ../HPI)"
if [[ ! -e "${MY_MODULES}" ]]; then
	echo "My Modules doesn't exist '${MY_MODULES}'" 1>&2
	exit 1
fi

source "${MY_MODULES}/install" 'source'
pmain "$@" || exit $?
