#!/usr/bin/env bash

# if this succeeds, a backup within the last week already exists
last_cstimer_backup() {
	local newest_file
	newest_file="$(newest "$(backup_to 'cubing/cstimer')")" || {
		echo 'Failed to find newest file'
		return 0
	}
	diff=$(($(epoch) - $(stat -c"%Y" "$newest_file")))
	# 604800 <=> 1 week
	if ((diff > 604800)); then
		return 1
	fi
	return 0
}

# https://github.com/seanbreckenridge/cstimer-save-server
# open cstimer, so that my solves are saved
# only do this if we havent already backed up in the last week
last_cstimer_backup || {
	openurl 'http://localhost:4633/'
}

cubers_io_files() {
	find "${XDG_DOWNLOAD_DIR:-$HOME/Downloads}/" -name '*twistytimer*' "$@"
}

# run this before exporting, so it doesnt move a partially downloaded
# file from downloads, it'll back it up next time I run the script
# (this is called in https://sean.fish/d/housekeeping?dark)
evry 1 hour -move-cubers-io && {
	to_dir="$(backup_to 'cubing/cubers_io')"
	cubers_io_files "$@"
	cubers_io_files -exec mv -t "$to_dir" {} +
}

# open the api export page, uses my logged in session and downloads the file
evry 4 weeks -save-cubers-io && {
	openurl 'https://www.cubers.io/api/export?type=twisty_timer'
}
