#!/usr/bin/env python3
# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "browserexport>=0.4.4",
#     "hpi[optional]>=0.7.20250911",
# ]
# ///

from typing import Iterator
from urllib.parse import urlparse

import click
from more_itertools import unique_everseen
from my.browser.active_browser import history as active_history
from my.browser.all import history


def urls(active: bool) -> Iterator[str]:
    func = active_history if active else history
    for hist in func():
        if not hist.url.startswith("https://github.com/"):
            continue
        parts = urlparse(hist.url)
        if parts.path.count("/") >= 2:
            path_parts = parts.path.strip("/").split("/")
            yield "https://github.com/" + "/".join(path_parts[0:2])


@click.command()
@click.option("--active/--all", default=True, is_flag=True, show_default=True)
def main(active: bool) -> None:
    for url in unique_everseen(urls(active)):
        print(url)


if __name__ == "__main__":
    main()
