#!/usr/bin/env python3

import click
from ttally.__main__ import event


@click.command()
@click.option("--sort-by", type=click.Choice(["when", "score"]), default="when")
def main(sort_by: str) -> None:
    for ev in sorted(
        event(),
        key=lambda x: x.when if sort_by == "when" else x.score,
        reverse=sort_by == "score",
    ):
        dt = ev.when.astimezone().strftime("%Y-%m-%d %H:%M")
        print(f"## {ev.description}\n{dt} | {ev.score}/10\n")


if __name__ == "__main__":
    main(prog_name="events-generate")
