#!/usr/bin/env python3

import click
from typing import Sequence
from ttally.__main__ import event


@click.command()
@click.option("--sort-by", type=click.Choice(["when", "score"]), default="when")
@click.option("--include-comments", is_flag=True, default=False)
@click.option("--filter-type", type=str, default=None, multiple=True)
def main(sort_by: str, include_comments: bool, filter_type: Sequence[str]) -> None:
    for ev in sorted(
        event(),
        key=lambda x: x.when if sort_by == "when" else x.score,
        reverse=sort_by == "score",
    ):
        if filter_type and ev.event_type not in filter_type:
            continue
        dt = ev.when.astimezone().strftime("%Y-%m-%d %H:%M")
        print(f"## {ev.description}\n{dt} | {ev.score}/10\n")
        if include_comments and ev.comments:
            print(ev.comments)
            print()


if __name__ == "__main__":
    main(prog_name="events-generate")
