#!/usr/bin/env python3
# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "click>=8.3.1",
#     "ttally>=0.1.4",
# ]
# ///

from typing import Sequence, NamedTuple, cast, TYPE_CHECKING
from datetime import datetime

import click
from ttally.__main__ import event

# stub copy for types
if TYPE_CHECKING:

    class Event(NamedTuple):
        event_type: str
        when: datetime
        description: str
        score: int | None
        comments: str | None

else:

    class Event:
        pass


@click.command()
@click.option("--sort-by", type=click.Choice(["when", "score"]), default="when")
@click.option("--include-comments", is_flag=True, default=False)
@click.option("--filter-type", type=str, default=None, multiple=True)
def main(sort_by: str, include_comments: bool, filter_type: Sequence[str]) -> None:
    data: list[Event] = cast(list[Event], list(event()))
    for ev in sorted(
        data,
        key=lambda x: x.when if sort_by == "when" else x.score or 0,
        reverse=sort_by == "score",
    ):
        if filter_type and ev.event_type not in filter_type:
            continue
        dt = ev.when.astimezone().strftime("%Y-%m-%d %H:%M")
        print(f"## {ev.description}\n{dt} | {ev.score}/10\n")
        if include_comments and ev.comments:
            print(ev.comments)
            print()


if __name__ == "__main__":
    main(prog_name="events-generate")
