#!/usr/bin/env python3
# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "cachew>=0.22.20251013",
#     "click>=8.3.1",
#     "colorlog>=6.10.1",
#     "hpi>=0.7.20250911",
#     "hpi-purarue>=0.1.0",
# ]
# ///

import my.zsh

import click


@click.command()
def main() -> None:
    for file in my.zsh.backup_inputs():
        for line in my.zsh._parse_file(file):
            if not line.dt:
                print(file, line)


if __name__ == "__main__":
    main()
