#!/usr/bin/env bash
# fuzzy search all my history (with descriptions, to help match what I'm looking for)

set -o pipefail

# additional jq after you pick with fzf removes quotes (-r)
#
# unique: https://sean.fish/d/unique?dark

URL="$(hpi query -s my.browser.all.history |
	jq '"\(.url)|\(.metadata.description)"' |
	unique |
	fzf +m --tac |
	jq -r |
	head -n 1 |
	cut -d"|" -f1)"

if [[ -n "${URL}" ]]; then
	echo "${URL}"
	hash clipcopy 2>/dev/null && clipcopy <<<"${URL}"
fi
