#!/usr/bin/env python3

import random
import click

from more_itertools import last
from my.location.gpslogger import inputs, _extract_locations


@click.command()
@click.option("-d", "--delim", help="char to use between characters", default=",")
@click.option("-p", "--precision", help="how many decimals", default=6)
@click.option("-f", "--fuzz", help="fuzz out the location", default=0, type=float)
def main(delim: str, precision: int, fuzz: float) -> None:
    latest = last(sorted(inputs(), key=lambda loc: loc.stat().st_mtime))
    latest_loc = last(sorted(_extract_locations(latest), key=lambda loc: loc.dt))
    lat = round(latest_loc.lat, precision)
    lon = round(latest_loc.lon, precision)
    lat += random.uniform(-fuzz, fuzz)
    lon += random.uniform(-fuzz, fuzz)
    if precision == 0:
        lat = int(lat)
        lon = int(lon)
        print(f"{lat}{delim}{lon}")
    else:
        print(f"{lat:.{precision}f}{delim}{lon:.{precision}f}")


if __name__ == "__main__":
    main()
