#!/usr/bin/env python3

"""
Print merged listens with a local datetime, using https://github.com/seanbreckenridge/my_feed
"""

import json
from datetime import datetime
from typing import Iterator

import click
from my.core.query_range import select_range, RangeTuple
from my_feed.sources.model import FeedItem
from my_feed.sources import mpv, listens


def sources() -> Iterator[FeedItem]:
    yield from mpv.history()
    yield from listens.history()


@click.command(help=__doc__)
@click.option(
    "-r",
    "--recent",
    default=None,
    help="only list items within this range",
)
@click.option(
    "-d",
    "--desc/--json",
    is_flag=True,
    help="Print single line description instead of JSON",
)
def main(recent: str | None, desc: bool) -> None:
    for ll in select_range(
        sources(),  # type: ignore
        order_by_value_type=datetime,
        unparsed_range=RangeTuple(before="now", within=recent, after=None),
        drop_exceptions=True,
    ):
        assert isinstance(ll, FeedItem)

        d = {
            "when": str(datetime.fromtimestamp(int(ll.when.timestamp()))),
            "title": ll.title,
            "artist": ll.creator,
            "album": ll.subtitle,
        }
        if desc:
            print(f"{d['when']} | {d['title']} | {d['artist']} | {d['album']}")
        else:
            print(json.dumps(d))


if __name__ == "__main__":
    main()
