#!/usr/bin/env python3

import click
from typing import Optional

from my.mal.export import anime, AnimeData


def seconds_left(a: AnimeData) -> Optional[int]:
    if a.APIList is None:
        return None
    if a.APIList.average_episode_duration is None:
        return None
    if a.XMLData.episodes == 0:
        return None
    eps_left = a.XMLData.episodes - a.XMLData.watched_episodes
    if eps_left <= 0:
        return None
    sl = a.APIList.average_episode_duration * eps_left
    if sl == 0:
        return None
    return sl


def seconds_sort_key(a: AnimeData) -> int:
    sl = seconds_left(a)
    if sl is None:
        return -1
    return sl


@click.command()
@click.option("--mal-username", envvar="MAL_USERNAME", required=True)
@click.option("--status", default="On-Hold", required=True)
def main(mal_username: str, status: str) -> None:
    an = list(
        filter(
            lambda a: a.XMLData.status == status
            and a.username == mal_username
            and a.APIList is not None
            and a.APIList.status == "finished_airing",
            anime(),
        )
    )
    an.sort(key=seconds_sort_key)
    for a in an:
        sl = seconds_left(a)
        if sl is None:
            continue
        click.echo(
            f"https://myanimelist.net/anime/{str(a.id).ljust(6)} | {str(sl//60).zfill(4)} min left | {a.XMLData.title} "
        )


if __name__ == "__main__":
    main()
