#!/usr/bin/env python3

import os
import click


@click.command()
@click.option(
    "-u",
    "--username",
    help="MAL username",
    envvar="MAL_USERNAME",
    required=True,
)
@click.option(
    "-e",
    "--export",
    help="Update export",
    is_flag=True,
)
@click.option(
    "-h",
    "--history",
    help="Update history",
    is_flag=True,
)
@click.option(
    "-m",
    "--manga-history",
    help="Update manga history",
    type=int,
    default=0,
)
@click.argument("HISTORY_COUNT", type=int, default=5)
def main(
    username: str,
    export: bool,
    history: bool,
    history_count: int,
    manga_history: int,
) -> None:

    from malexport.list_type import ListType
    from malexport.exporter.account import Account

    account = Account.from_username(username)

    if export or not (export or history):
        click.echo("Updating export...", err=True)
        account.update_exports()

    if history or not (export or history):
        click.echo("Updating history...", err=True)
        account.update_history(
            count=history_count, only=ListType.ANIME, use_merged_file=True
        )

    if manga_history > 0:
        click.echo("Updating manga history...", err=True)
        account.update_history(
            count=manga_history, only=ListType.MANGA, use_merged_file=True
        )


if __name__ == "__main__":
    main(prog_name="malexport_partial_update")
