#!/usr/bin/env bash
# if -e is provided, just does export
# if -h is provided, just does history
# otherwise, does both

main() {
	local rexport history noflags
	rexport=''
	history=''
	noflags=''
	while getopts eh opt; do
		case "$opt" in
		e)
			rexport=1
			;;
		h)
			history=1
			;;
		*) ;;
		esac
	done
	shift "$((OPTIND - 1))"
	[[ -z "$rexport" && -z "$history" ]] && noflags=1
	if [[ -n "$rexport" || -n "$noflags" ]]; then
		echo 'Running export...' >&2
		malexport update export -u "$MAL_USERNAME" || return $?
	fi
	if [[ -n "$history" || -n "$noflags" ]]; then
		echo 'Downloading recent history...' >&2
		MALEXPORT_EPISODE_LIMIT="${1:-1}" malexport update history -u "$MAL_USERNAME" -o anime -c "${2:-5}" || return $?
	fi
}

main "$@" || exit $?
