#!/usr/bin/env python3
# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "hpi[optional]>=0.7.20250911",
#     "hpi-purarue>=0.1.0",
#     "mpv-history-daemon>=0.2.6",
#     "plaintext-playlist-py>=0.1.0",
# ]
# ///

from datetime import datetime

from my.mpv.history_daemon import history


def to_naive(dt: datetime) -> datetime:
    return datetime.fromtimestamp(dt.timestamp())


def main() -> None:
    for m in history():
        print(f"{to_naive(m.start_time)} {m.path}")


if __name__ == "__main__":
    main()
