#!/usr/bin/env python3
# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "browserexport>=0.4.4",
#     "more-itertools>=10.8.0",
#     "pyfzf-iter>=0.0.1",
#     "pyperclip>=1.11.0",
#     "sqlite-backup>=0.1.8",
# ]
# ///


import json
from typing import Any

import click
from browserexport.browsers.firefox import Firefox
from browserexport.parse import read_visits
from sqlite_backup.core import sqlite_backup
from more_itertools import unique_everseen
from pyfzf import FzfPrompt
from pyperclip import copy  # type: ignore
from webbrowser import open_new_tab


def visits() -> Any:
    conn = sqlite_backup(Firefox.locate_database())
    assert conn is not None
    for visit in unique_everseen(read_visits(conn), key=lambda v: v.url):
        yield json.dumps(
            {
                "url": visit.url,
                "metadata": getattr(visit.metadata, "description", ""),
            }
        )


@click.command()
def main() -> None:
    fzf = FzfPrompt(default_options="+m --tac")
    chosen = fzf.prompt(visits())
    if chosen:
        url = json.loads(chosen[0])["url"]
        click.echo(url)
        copy(url)
        open_new_tab(url)


if __name__ == "__main__":
    main()
