#!/usr/bin/env python3
# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "click>=8.3.1",
#     "colorlog>=6.10.1",
#     "hpi>=0.7.20250911",
#     "lxml>=6.0.2",
# ]
# ///

import os
import re
import base64

from my.smscalls import mms

import click


def slugify(s: str) -> str:
    s = s.lower()
    s = re.sub("[~,+]", "_", s)
    return s[:128]


cache_dir = os.environ.get("XDG_CACHE_HOME", os.path.expanduser("~/.cache"))
app_cache_dir = os.path.join(cache_dir, "sms-images")


ALLOWED_FILETYPES = {
    "video/3gpp": ".3gpp",
    "image/gif": ".gif",
    "image/jpeg": ".jpg",
    "image/png": ".png",
    "video/mp4": ".mp4",
}


@click.command()
def main() -> None:
    size = 0
    items = 0

    for msg in mms():
        if isinstance(msg, Exception):
            continue
        datestr = f"{msg.dt.timestamp()}"
        for part in msg.parts:
            if part.data is None:
                continue
            if part.content_type not in ALLOWED_FILETYPES:
                continue
            data = base64.b64decode(part.data)
            extension = ALLOWED_FILETYPES[part.content_type]
            # folder with the phone_number (sort of like a hash)
            output_filedir = os.path.join(app_cache_dir, slugify(msg.phone_number))
            os.makedirs(output_filedir, exist_ok=True)
            # date -> filename . extension
            output_filename = os.path.join(
                output_filedir, f"{datestr}-{part.filename}{extension}"
            )
            if not os.path.exists(output_filename):
                click.echo(f"Saving {output_filename}")
                with open(output_filename, "wb") as f:
                    f.write(data)

                # set modification time to when the message was sent
                os.utime(output_filename, (msg.dt.timestamp(), msg.dt.timestamp()))

            st = os.stat(output_filename)
            size += st.st_size
            items += 1

    click.echo(
        f"{click.style('sms-images', 'green')}: Done, cache has {items} images, using {round(size / 1024 / 1024, 3)} MB"
    )


if __name__ == "__main__":
    main(prog_name="sms-images")
