#!/usr/bin/env bash

wait-for-internet -q --timeout "${WFI_TIMEOUT:-10}" || exit 0

evry 2 hours -backup_trakt_partial && {
	BACKUP_DIR="$(backup_to trakt)"
	printlog "traktexport:Running partial export..."
	arctee -r 3 "${BACKUP_DIR}/${ON_OS}-partial.json" -- python3 -m traktexport partial_export purplepinapples --days 7 || send-error 'traktexport: failed to run partial export'
	json-compress "${BACKUP_DIR}/"*.json
}
